name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Publish Release artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Extract git tag
        shell: bash
        run: |
          echo "RELEASE_TAG=$(git tag --points-at HEAD)" >> "$GITHUB_ENV"

      - name: Download artifacts from latest workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          branch: ${{ github.event.release.target_commitish }}
          workflow_conclusion: success
          skip_unpack: false

      - name: Rename build artifacts
        run: |
          cd tricore-gdb
          zip -rX9 tricore-gdb.zip ./*
          mv tricore-gdb.zip tricore-gdb-${{ env.RELEASE_TAG }}.zip

      - name: Push release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tricore-gdb/*.zip